[package]
name = "iml-device"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
device-tree-merger = { path = "../../device-tree-merger" }
device-types = { version = "0.1", git = "https://github.com/whamcloud/device-scanner.git" }
diesel = { version = "1.4", default_features = false, features = ["postgres", "r2d2", "chrono", "serde_json"] }
futures = "0.3"
im = { version = "13.0", features = ["serde"] }
iml-manager-env = { path = "../../iml-manager-env", version = "0.2.0" }
iml-orm = { path = "../../iml-orm", version = "0.2.0", features = ["postgres-interop"] }
iml-postgres = { path = "../../iml-postgres", version = "0.2.0" }
iml-rabbit = { path = "../../iml-rabbit", version = "0.2.0" }
iml-service-queue = { path = "../iml-service-queue", version = "0.2.0" }
iml-tracing = { version = "0.1", path="../../iml-tracing"}
iml-wire-types = { path = "../../iml-wire-types", version = "0.2", features = ["postgres-interop"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
tokio-util = { version = "0.3", features = ["codec"] }
treediff = { git = "https://github.com/whamcloud/treediff-rs.git", branch = "key-serde", version = "4.0.0", features = ["with-serde-json"] }
tracing = "0.1"
warp = "0.2"
chrono = "0.4.11"

[dev-dependencies]
insta = "0.16"
test-case = "1.0.0"
tracing-subscriber = "0.2.5"
